### ISSUE TITLE
max wifi speed limited to 56Mbit?

### ISSUE THREAD

**Issue by aparcar** [bmx-routing/bmx7#11]
https://github.com/bmx-routing/bmx7/blob/1b8cf4c119d3bf886a9b9c5a1bca8043506f3684/ip.h#L164

Is it possible that this value is outdated?

**Comment by axn** [comment]
if bmx7_iwinfo.so plugin is loaded then a indeed better assumptions can be made and the configured rateMax value is ignored. But, as long a no better assumptions can be made (no mac or phy infor available), this value is still reasonable.
Anyway, It can easily be overwritten with like: 'bmx7 -c dev=wlan0 /rateMax=150000000

Which value would you suggest? Consider that 11a and 11g should still be supported and reflected.

**Comment by axn** [comment]
Closing issue for now

**Comment by aparcar** [comment]
Does this output mean that even tho the estimated max rate is 130Mbit it's capped to 56Mbit due to the max rate setting of a wifi interface?

```
root@meshrc-middle:~# bmx7 -c s=l s=i
LINKS:
shortId  name        linkKey    linkKeys          nbLocalIp                 dev           rts rq tq txRate wTxRate wTxRateEff wTxThr wTxThrEff mcs sgi chw wSnr
7069125B meshrc-open DH2048M112 RSA896,DH2048M112 fe80::cee1:d5ff:fe92:dadb wlan1-mesh_13 3   76 74 7930K  130M    7930K      45750K 4884K     6   1   20  -26
INTERFACES:
dev           state linkKey    linkKeys          type     channel rateMax idx localIp                     rts helloSqn rxBpP   txBpP
br-lan        UP    DH2048M112 RSA896,DH2048M112 ethernet 0       1000M   1   fe80::7603:bdff:fe31:e80/64 0   44555    0/0.0   110/1.3
wlan1-mesh_13 UP    DH2048M112 RSA896,DH2048M112 wireless 128     56000K  2   fe80::7603:bdff:fe31:e82/64 3   56437    208/1.4 176/1.4
```
