### ISSUE TITLE
add shortId and name to dns

### ISSUE THREAD

**Issue by aparcar** [bmx-routing/bmx7#16]
It would be nice to add the shortId and hostnames as DNS entries pointing to the crypto IPv6.
This can be archived with the following command, but maybe there's a cleaner way?

```
bmx7 -c originators | tail -n +3 | awk '{ print $13" "$13 }' > /tmp/hosts/bmx7_shortId
bmx7 -c originators | tail -n +3 | awk '{ print $13" "$12 }' > /tmp/hosts/bmx7_hostname
/etc/init.d/dnsmasq reload
```

**Comment by axn** [comment]
Duplicate https://github.com/openwrt/packages/pull/5923
