### ISSUE TITLE
bmx7_uci_config: auto reload on changes

### ISSUE THREAD

**Issue by aparcar** [bmx-routing/bmx7#17]
is it possible to make bmx7 watch the uci config file?
another way is to give bmx7 the actions via `-c` and let bmx7 sync the settings - is that preferred?

**Comment by axn** [comment]
The reason to not sync automatically after a given 'bmx7 -c ...' command is that temporary settings could be reverted with 'uci revert bmx7' (To make them persistent call 'uci bmx7 commit') If settings are applied with 'uci set bmx7...' they could be applied with 'bmx7 -c configReload'

**Comment by aparcar** [comment]
ack
