### ISSUE TITLE
Useless 	if (currSqn == 0) { check

### ISSUE THREAD

**Issue by aparcar** [bmx-routing/bmx7#29]
https://github.com/bmx-routing/bmx7/blob/3df0a26e3247361097c9207a4c248f40bf7bfe0f/bmx.c#L1430
https://github.com/bmx-routing/bmx7/blob/3df0a26e3247361097c9207a4c248f40bf7bfe0f/bmx.c#L1449

Isn't currSqn set to zero just before and so this if doesn't do anything but always equal true?

**Comment by axn** [comment]
No, if a variable in c is declared static it is initialized only once and keeps its last (re-)assignement till program termination.

**Comment by aparcar** [comment]
Thanks for the clarification!
