### ISSUE TITLE
SMS plugin

### ISSUE THREAD

**Issue by mozartatplay** [bmx-routing/bmx7#32]
I've been testing the SMS plugin but can't seem to get any result

My testing environment is https://github.com/axn/mlc

I started bmx7 on all nodes with
mlc_loop -i 1000 -a 1008 -e "bmx7 dev=eth1.11"
mlc_configure_line 1

I checked /etc/config/bmx7 to see if sms plugin is enabled

config 'plugin'
            option 'plugin' 'bmx7_sms.so'

I connect to a mlc1000, added a file with 8 characters in /var/run/bmx7/sms/sendSms 
I then connect to node mlc1001 and look in /var/run/bmx7/sms/rcvdSms

But the file does not propagate 

Is there something I am missing?

**Comment by aparcar** [comment]
Yes, you have to actively tell bmx7 to distribute it.

```
bmx7 -c syncSms="<filename without path>"
```

**Comment by mozartatplay** [comment]
Sorry about that .. I see that option now in the help file but it wasn't  clear from the help file that this is a file to send without the path. Can I suggest changing the SMS plugin section of the Readme to

The API of the sms plug-in is very simple. It simply clones the content of one or more files given by one node to all other nodes. All other nodes can do the same. Once started, each node will have two directories:/var/run/bmx7/sms/rcvdSms and /var/run/bmx7/sms/sendSms. 

Files are cloned from the sendSms folder on the current node to the rcvdSmS folder on all other nodes with the syncSms option using the following steps
1. Place files you want to send in the sendSms folder
2. Use the syncSms option in bmx7 to send the file
bmx7 -c syncSms="<filename placed in the sendSms folder>"

Wireless-mesh distros are using this feature for several things such as positioning Map information or a chat in web interface.

**Comment by aparcar** [comment]
Updated, thanks!

**Comment by mozartatplay** [comment]
Awesome thanks
