### ISSUE TITLE
Add introduction to documentation

### ISSUE THREAD

**Issue by sarumpaet** [bmx-routing/bmx7#44]
The README is missing a quick introduction and feature set. This should be the very first lines. How does bmx7 work, very briefly? On what OSI layer? What software is similar? What are bmx's special/most noteworthy features? What are the differences to bmx6? (if someone gives those details here, I can create a PR)

In the GitHub project description (at the top of https://github.com/bmx-routing/bmx7 ) there should probably also be a link to the homepage or the README (which otherwise gets a bit lost below all the source files).

**Comment by luserx0** [comment]
To synopsize:
- How does BMX7 work and on which OSI layer?
- Similar Software
- Cool features
- Differences with bmx6

I empathize with getting lost with all the source files at the root tree of the repo. Moving them to an src destination would be much favorable. 

If you have more questions related to bmx7 please post them here and they will all be answered (if the volume gets big enough we can create an FAQ)
