### ISSUE TITLE
bmx7 on OpenWrt stable 18.06.04 nlmsg_len messages

### ISSUE THREAD

**Issue by imp1sh** [bmx-routing/bmx7#47]
Hi,
I'm running a research simulated network of currently 41 OpenWrt Nodes x86_64 virtualized with Proxmox and bmx7 installed via <code>opkg install</code>.
The logs are full of those messages:
```
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1276  old=1276
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1556  old=1556
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: INFO  kernel_get_if_link_config(): CHANGED nlmsg_len new=1280  old=1280
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22200] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22201] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1556  old=1556
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22202] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22203] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22204] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22205] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22206] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22207] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22208] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22209] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1284  old=1284
Aug 10 10:56:17 n41 bmx7[1835]: [1835 83293315 22210] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
```
What does they mean and how can I get rid of them? This is my uci config:
```
config bmx7 'general'

config dev 'neigh3'
        option dev 'eth7'

config dev 'neigh2'
        option dev 'eth6'

config dev 'neigh1'
        option dev 'eth5'

config dev 'neigh0'
        option dev 'eth4'

config dev 'neigh4'
        option dev 'eth8'

config plugin

config plugin
        option plugin 'bmx7_config.so'

config plugin
        option plugin 'bmx7_sms.so'

config plugin
        option plugin 'bmx7_json.so'

config plugin
        option plugin 'bmx7_topology.so'

```
Those are the packages installed:
```
bmx7 - r2018122901-1
bmx7-dnsupdate - 0.1-2
bmx7-json - r2018122901-1
bmx7-sms - r2018122901-1
bmx7-table - r2018122901-1
bmx7-topology - r2018122901-1
bmx7-tun - r2018122901-1
bmx7-uci-config - r2018122901-1
luci-app-bmx7 - 0.1-alpha
```
Edit:
This also happens to me on <code>OpenWrt SNAPSHOT r10718-54449622c9</code> and those packages:
```
bmx7 - r2019030802-1
bmx7-dnsupdate - 0.1-2
bmx7-json - r2019030802-1
bmx7-sms - r2019030802-1
bmx7-topology - r2019030802-1
bmx7-tun - r2019030802-1
bmx7-uci-config - r2019030802-1
luci-app-bmx7 - git-19.222.06794-9def6fa-1
```

**Comment by FreifunkUFO** [comment]
yes, we can see that too, on a openwrt-driven mesh-node community-mesh with physically existing nodes (Freifunk Leipzig Plagwitz)

`
root@fr-m5:/www/cgi-bin# logread | grep bmx7
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7961] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7962] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7963] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7964] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7965] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7966] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7967] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7968] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7969] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7970] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7971] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 18:40:01 2020 daemon.info bmx7[1412]: [1412 275246845  7972] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7973] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7974] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7975] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7976] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7977] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7978] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7979] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7980] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7981] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7982] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7983] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 18:50:01 2020 daemon.info bmx7[1412]: [1412 275846879  7984] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7985] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7986] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7987] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7988] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7989] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7990] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7991] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7992] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7993] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7994] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7995] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 19:00:01 2020 daemon.info bmx7[1412]: [1412 276446936  7996] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 19:04:14 2020 daemon.info bmx7[1412]: [1412 276697052  7997] WARN  : critical system time drift detected: ++ approx 1 s, 813834 us! Correcting reference!
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  7998] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  7999] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8000] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8001] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8002] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8003] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8004] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8005] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8006] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8007] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8008] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 19:10:00 2020 daemon.info bmx7[1412]: [1412 277044213  8009] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8010] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8011] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8012] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8013] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8014] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8015] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8016] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8017] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8018] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8019] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8020] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 19:20:00 2020 daemon.info bmx7[1412]: [1412 277644265  8021] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8022] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8023] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8024] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8025] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8026] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8027] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8028] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8029] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8030] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8031] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8032] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 19:30:00 2020 daemon.info bmx7[1412]: [1412 278244355  8033] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8034] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8035] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8036] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8037] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8038] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8039] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8040] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8041] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8042] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8043] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1344  old=1344
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8044] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1276  old=1276
Mon Jun  8 19:40:00 2020 daemon.info bmx7[1412]: [1412 278844383  8045] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1464  old=1464
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8046] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1272  old=1272
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8047] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1280  old=1280
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8048] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1456  old=1456
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8049] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1720  old=1720
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8050] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1616  old=1616
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8051] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=1332
Mon Jun  8 19:50:00 2020 daemon.info bmx7[1412]: [1412 279444442  8052] INFO  kernel_get_if_link_config: CHANGED nlmsg_len new=1332  old=133`

**Comment by axn** [comment]
The messages are uncritical. I guess some of the linux network interface
configuation has changed and bmx7 detected that. I'll lower their
relevance so that they are not printed to system logs (logread) anymore.

**Comment by FreifunkUFO** [comment]
* messages are every 10 minutes on our network. where does it come from?
* the new / old values inside the log messages are not correctly printed. either the new or the old value is wrong

**Comment by nickbash11** [comment]
I join to this issue, my logs from all routers are collecting to one machine and these messages are flooding all the log memory, it's bad

**Comment by imp1sh** [comment]
21.02 also suffers this issue.
bmx7 - 7.1.1-4

**Comment by axn** [comment]
Should be fixed with commit
https://github.com/bmx-routing/bmx7/commit/f186bf5a0fde6e041edcef20c50bf5ddf2b5e1a5
