### ISSUE TITLE
bmx7 compile on debian 10

### ISSUE THREAD

**Issue by imp1sh** [bmx-routing/bmx7#48]
Is bmx7 supposed to compile on Debian, too?
I tried to compile it and after meeting the requirements it installed into /usr/sbin/bmx7 after make install.
Sadly when I invoke bmx7 I get
<code>bmx7 --help
Bus error (core dumped)
</code>

I tried this one release bmx7-7.1.0.tar.gz and I tried commit 91d6651ccb5a563d4752f719f7a892512079093d. The result is always the same.

This is how I built:
<code>make EXTRA_CFLAGS="-DCRYPTLIB=MBEDTLS_2_4_0"</code>

**Comment by luserx0** [comment]
> Is bmx7 supposed to compile on Debian, too?
Definitely yes.

I just reproduced this on my debian-10 VM and everything runs as expected.

Could you provide a more step by step description of your approach?

Did you follow the README directives? Did you try cloning the GitHub repo at the current commit of master?

**Comment by imp1sh** [comment]
I need to check out the repository from another machine, because the target I want to compile on is IPv6 only and github won't do IPv6 sadly. Then I copy it via scp (mc actually) to the target device.
I Install plenty of software like asked for in the ReadMe via apt, like those:
libiw-dev libjson-c-dev build-essential libmbedtls12 libmbedtls-dev libiw-dev
Then I go into the src directory and run this:
make EXTRA_CFLAGS="-DCRYPTLIB=MBEDTLS_2_4_0"
and then I run ./bmx7 in the same directory. The error shows up.
It's virtualized Debian 10 (qemu) on Proxmox 6. Don't know if that might be important.

**Comment by imp1sh** [comment]
It's working now. Don't know exactly what was wrong, maybe the fact that I had mbedtls 2.4 installed from sources as well as this libmbedtls-dev via dpkg1, dunno exactly.
Apart from that I also tried mbedtls 2.16 but that didn't work either.
