### ISSUE TITLE
table plugin build fail.

### ISSUE THREAD

**Issue by db4rne** [bmx-routing/bmx7#54]
When I try to build the table plugin in Arch linux, i get the following error:

```
../../redist.c:76:17: error: ‘struct avl_node’ has no member named ‘right’
   76 |   p->more = (ran->right ? YES : NO);
      |                 ^~
../../redist.c: In function ‘redist_rm_overlapping’:
```

I don't quite get why it shouldn't have that member, since `CFLAGS += -DAVL_5XLINKED` is set in Common.mk

**Comment by axn** [comment]
Can't reproduce. For me it compiles in debian and openwrt. Please reopen if still exists
