### ISSUE TITLE
/var/run/bmx7/json/descriptions empty

### ISSUE THREAD

**Issue by aparcar** [bmx-routing/bmx7#6]
The json descriptions of nodes are empty
 
    root@LiMe-d0cc2a:~# cat /var/run/bmx7/json/descriptions/5FA90DD26826D3DF98BF12271FB8B00C7DB7F25DB3FEF6C7D60B49C2 
    { "descSha": "F85C6A16CA64103584385DE48C0F0A00665073948D826F8489BEA5D5" }

**Comment by axn** [comment]
Should be fixed with https://github.com/bmx-routing/bmx7/commit/c9cf16e5ee2a994de9e909444129899d950d98b7
